name: Run all test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - run: npm ci
    - run: npm run build
    - run: npm test
      env: 
        DB_TEST_CONNECTION: ${{secrets.DB_TEST_CONNECTION}}
